language: node_js

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - nvm install

install:
  - yarn install

script:
  - yarn lint:scripts
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: bash bin/deploy.sh
#   on:
#     branch: develop
