language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
    - braican.com
    - 69.164.211.156
before_install:
- openssl aes-256-cbc -K $encrypted_ea2966dd748b_key -iv $encrypted_ea2966dd748b_iv -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_rsa
- ssh-add .travis/deploy_rsa
- nvm install
install:
- npm install
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: bash .deploy
  on:
    branch: setup
