language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_ea2966dd748b_key -iv $encrypted_ea2966dd748b_iv
  -in ./travis/deploy_rsa.enc -out ./travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
- nvm install
install:
- npm install
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build braican@69.164.211.156:/var/www/tk2
  on:
    branch: setup
