[build]
command = "yarn build"
functions = "functions/"
publish = "build"

[dev]
command = "yarn react-start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
